import os


AWS_S3_BUCKET_NAME = "waferprojfinal"
MONGO_DATABASE_NAME = "Wafer"
MONGO_COLLECTION_NAME = "Wafer_Fault"
MONGODB_URL_KEY = "MONGODB_URL"



TARGET_COLUMN = "quality"



MODEL_FILE_NAME = "model"
MODEL_FILE_EXTENSION = ".pkl"

ARTIFACT_FOLDER =  "artifacts"

AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
REGION_NAME = "us-east-1"




